### ISSUE TITLE
Why is Hypex an application?

### ISSUE THREAD

**Issue by garthk** [whitfin/hypex#1]
G'day! Elixir newcomer here, kicking the tyres because I think I might need a HyperLogLog to avoid blowing out the size of a term counter when the vast majority of counts will be 1. One thing I don't understand given my study to date:

> Ensure hypex is started before your application:

Why? Did that happen automatically when I ran `iex -S mix`? Because, the rest of the code worked fine without that step.

**Comment by whitfin** [comment]
@garthk Yes, that happens automatically when you run that command. It's not strictly necessary, except;

* If it ever becomes necessary, it's not a breaking change.
* It allows your application to include the Hypex library. In older Elixir versions this was a requirement.

**Comment by garthk** [comment]
That all makes sense. Cheers!
